In [1]:
import sys
sys.path.insert(0, '../')
import numpy as np
%reload_ext autoreload
%autoreload 1
%aimport allel
%aimport allel.model
%aimport allel.bcolz
allel.__version__

'0.15.0.dev3'

In [2]:
# setup an array of genotype calls
shape = n_variants, n_samples, ploidy = 50000, 1000, 2
data = np.zeros(shape, dtype='i1')
# simulate some mutations
n_alleles = n_variants * n_samples * ploidy
idx = np.random.randint(0, (n_alleles//2)-1, size=n_alleles//20)
data[:, :, 1].reshape((-1))[idx] = 1
data[:, :, 0].reshape((-1))[idx[:n_alleles//200]] = 1
g = allel.model.GenotypeArray(data, copy=False)

In [3]:
g

GenotypeArray((50000, 1000, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 0]
  ...,
  [0 1]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 1]
  ...,
  [0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]
  ...,
  [0 0]
  [0 1]
  [0 0]]

 ...,
 [[0 0]
  [0 0]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 0]]

 [[1 1]
  [0 1]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 1]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 0]]]

In [4]:
h = g.to_haplotypes()
h

HaplotypeArray((50000, 2000), dtype=int8)
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 1]
 [0 0 0 ..., 1 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [1 1 0 ..., 0 0 1]
 [0 0 0 ..., 0 0 0]]

In [5]:
gc = allel.bcolz.GenotypeCArray(g)
gc

GenotypeCArray((50000, 1000, 2), int8)
  nbytes: 95.37 MB; cbytes: 15.97 MB; ratio: 5.97
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[[[0 0]
  [0 0]
  [0 0]
  ...,
  [0 1]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 1]
  ...,
  [0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 0]
  ...,
  [0 0]
  [0 1]
  [0 0]]

 ...,
 [[0 0]
  [0 0]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 0]]

 [[1 1]
  [0 1]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 1]]

 [[0 0]
  [0 1]
  [0 0]
  ...,
  [0 0]
  [0 0]
  [0 0]]]

In [6]:
hc = gc.to_haplotypes()
hc

HaplotypeCArray((50000, 2000), int8)
  nbytes: 95.37 MB; cbytes: 15.97 MB; ratio: 5.97
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 1]
 [0 0 0 ..., 1 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [1 1 0 ..., 0 0 1]
 [0 0 0 ..., 0 0 0]]

In [7]:
ac = g.count_alleles()
ac

AlleleCountsArray((50000, 2), dtype=int32)
[[1900  100]
 [1893  107]
 [1905   95]
 ...,
 [1911   89]
 [1899  101]
 [1873  127]]

In [9]:
gac = gc.count_alleles()
gac

AlleleCountsCArray((50000, 2), int32)
  nbytes: 390.62 KB; cbytes: 321.33 KB; ratio: 1.22
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[[1900  100]
 [1893  107]
 [1905   95]
 ...,
 [1911   89]
 [1899  101]
 [1873  127]]